name: Build

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build
        run:  |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload release asset
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*-+([0-9]).+([0-9]).+([0-9])-+([0-9]).+([0-9]).+([0-9]).jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}